baseURL: "/"
languageCode: "en-us"
title: "H-Bop"
theme: "minimal-mod"
disqusShortname: "" # delete this to disable disqus comments
googleAnalytics: ""
sectionPagesMenu: "main"

params:
  author: "Roger Parent"
  description: "A Gulp 4 + Hugo Boilerplate"
  githubUsername: "#"
  showBorder: true
  backgroundColor: "white"
  font: "Raleway" # should match the name on Google Fonts!

menu:
  main:
    - url: "/"
      name: "Home"
      weight: 1

  # Social icons to be shown on the right-hand side of the navigation bar
  # The "name" field should match the name of the icon to be used
  # The list of available icons can be found at http://fontawesome.io/icons/

  icon:
    - url: "mailto:me@example.com"
      name: "envelope-o"
      weight: 1
  
    - url: "https://github.com/username/"
      name: "github"
      weight: 2
  
    - url: "https://twitter.com/username/"
      name: "twitter"
      weight: 3
  
    - url: "https://www.linkedin.com/in/username/"
      name: "linkedin"
      weight: 4
  
    - url: "https://www.stackoverflow.com/username/"
      name: "stack-overflow"
      weight: 5
